# Generated by Django 4.2.1 on 2023-05-24 12:59

from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.forms.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistrationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('zoom_event', models.TextField(blank=True, help_text='Select Zoom Event', null=True, verbose_name='Zoom Event')),
                ('zoom_reg_fields_mapping', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page'),
        ),
    ]
