# Generated by Django 4.2.1 on 2024-04-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailzoom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoomsettings',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='zoomsettings',
            name='api_secret',
        ),
        migrations.AddField(
            model_name='zoomsettings',
            name='oauth_account_id',
            field=models.CharField(blank=True, help_text='Account ID obtained from Zoom Server-to-Server OAuth', max_length=256, null=True, verbose_name='Zoom OAUTH Account ID'),
        ),
        migrations.AddField(
            model_name='zoomsettings',
            name='oauth_client_id',
            field=models.CharField(blank=True, help_text='Client ID obtained from Zoom Server-to-Server OAuth', max_length=256, null=True, verbose_name='Zoom OAUTH Client ID'),
        ),
        migrations.AddField(
            model_name='zoomsettings',
            name='oauth_client_secret',
            field=models.CharField(blank=True, help_text='Client Secret obtained from Zoom Server-to-Server OAuth', max_length=256, null=True, verbose_name='Zoom OAUTH Client Secret'),
        ),
    ]
